# Generated by Django 5.1 on 2024-09-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('category_thumbnail', models.ImageField(upload_to='category_thumbnail')),
            ],
        ),
    ]
