# Generated by Django 5.1 on 2024-09-29 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallery',
            name='productID',
        ),
        migrations.AddField(
            model_name='productgallery',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='backend.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='gallery_image',
            field=models.FileField(blank=True, null=True, upload_to='product_gallery/'),
        ),
    ]
