# Generated by Django 5.1 on 2024-09-30 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_brand_cart_created_at_alter_cart_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='category_thumbnail',
            new_name='thumbnail',
        ),
    ]
