# Generated by Django 5.1 on 2024-09-26 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_author_created_at_blog_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
    ]
