# Generated by Django 5.1 on 2024-11-14 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_document'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='UploadFile',
        ),
    ]
